# -*- coding: utf-8 -*-
"""Taller 1 Metodos 26A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqaJxluwFIRswwMdTiVTa0K4uNikBUTB
"""

# ============================================
# 1. IMPORTACIONES
# ============================================
import sympy as sp

# ============================================
# 2. FUNCIÓN GENERAL DE CENTRO DE MASA
# ============================================

def centro_de_masa(posiciones, masas):
    """
    posiciones: lista de tuplas o vectores (x,y) o (x,y,z)
    masas: lista de masas correspondientes

    Retorna: vector posición del centro de masa
    """
    if len(posiciones) != len(masas):
        raise ValueError("El número de posiciones y masas debe coincidir")

    # Convertimos todo a vectores sympy
    posiciones = [sp.Matrix(p) for p in posiciones]

    M_total = sum(masas)

    # Inicializamos la suma con un vector cero de las dimensiones correctas
    # para evitar TypeError al sumar un int con un sympy.Matrix.
    R_cm = sum((m * r for m, r in zip(masas, posiciones)), sp.zeros(posiciones[0].shape[0], 1)) / M_total

    return sp.simplify(R_cm)

# ============================================
# 3. EJERCICIO (a)
# Masas 1,2,3,4 en los vértices de un cuadrado
# lado a = 2
# ============================================

a = sp.symbols('a')

# Definimos los vértices del cuadrado en el plano XY
pos_cuadrado = [
    (0, 0),
    (a, 0),
    (a, a),
    (0, a)
]

masas_cuadrado = [1, 2, 3, 4]

R_cm_cuadrado = centro_de_masa(pos_cuadrado, masas_cuadrado)

print("Centro de masa (cuadrado):")
sp.pprint(R_cm_cuadrado)

# ============================================
# 4. EJERCICIO (b)
# Cubo de lado a
# Masas 1-4 abajo, 5-8 arriba
# ============================================

pos_cubo = [
    (0, 0, 0),
    (a, 0, 0),
    (a, a, 0),
    (0, a, 0),
    (0, 0, a),
    (a, 0, a),
    (a, a, a),
    (0, a, a)
]

masas_cubo = [1, 2, 3, 4, 5, 6, 7, 8]

R_cm_cubo = centro_de_masa(pos_cubo, masas_cubo)

print("\nCentro de masa (cubo):")
sp.pprint(R_cm_cubo)

# ============================================
# 1. IMPORTACIONES
# ============================================

import sympy as sp

# ============================================
# 2. FUNCIONES GENERALES
# ============================================

def magnitud(v):
    return sp.sqrt(v.dot(v))

def angulo_info(v, w):
    cos_theta = sp.simplify(v.dot(w) / (magnitud(v)*magnitud(w)))
    theta = sp.acos(cos_theta)
    return cos_theta, theta

def proyeccion(v, w):
    return sp.simplify((v.dot(w)/w.dot(w)) * w)

def producto_triple(v1, v2, v3):
    return sp.simplify(v1.dot(v2.cross(v3)))

# ============================================
# 3. DEFINICIÓN DE VECTORES
# ============================================

a = sp.Matrix([1,2,3])
b = sp.Matrix([4,5,6])
c = sp.Matrix([3,2,1])
d = sp.Matrix([6,5,4])

vectores = {"a":a, "b":b, "c":c, "d":d}

e1 = sp.Matrix([1,0,0])
e2 = sp.Matrix([0,1,0])
e3 = sp.Matrix([0,0,1])

# ============================================
# (a) SUMAS
# ============================================

print("\n--- (a) SUMAS ---")
print("a + b + c + d =", (a+b+c+d).tolist())
print("a + b - c - d =", (a+b-c-d).tolist())
print("a - b + c - d =", (a-b+c-d).tolist())
print("-a + b - c + d =", (-a+b-c+d).tolist())

# ============================================
# (b) ÁNGULOS CON LA BASE
# ============================================

print("\n--- (b) ÁNGULOS CON LA BASE ---")

for nombre, v in vectores.items():
    print(f"\nVector {nombre}:")

    for base_nombre, base in [("e1", e1), ("e2", e2), ("e3", e3)]:
        cos_t, theta = angulo_info(v, base)
        print(f"  Con {base_nombre}:")
        print("    cos(θ) =", cos_t)
        print("    θ =", sp.N(theta, 4), "rad")

# ============================================
# (c) MAGNITUDES
# ============================================

print("\n--- (c) MAGNITUDES ---")

for nombre, v in vectores.items():
    print(f"|{nombre}| =", sp.N(magnitud(v), 4))

# ============================================
# (d) ÁNGULOS ENTRE VECTORES
# ============================================

print("\n--- (d) ÁNGULOS ENTRE VECTORES ---")

cos_t, theta = angulo_info(a,b)
print("Entre a y b:")
print("  cos(θ) =", cos_t)
print("  θ =", sp.N(theta,4), "rad")

cos_t, theta = angulo_info(c,d)
print("\nEntre c y d:")
print("  cos(θ) =", cos_t)
print("  θ =", sp.N(theta,4), "rad")

# ============================================
# (e) PROYECCIÓN
# ============================================

print("\n--- (e) PROYECCIÓN DE a SOBRE b ---")
print("Proyección =", proyeccion(a,b).tolist())

# ============================================
# (f) COPLANARIDAD (PRODUCTO TRIPLE)
# ============================================

print("\n--- (f) PRODUCTO TRIPLE ---")
print("a · (b × c) =", producto_triple(a,b,c))

# ============================================
# (g) PRODUCTO ESCALAR COMPUESTO
# ============================================

print("\n--- (g) (a+b) · (c+d) ---")
print("(a+b)·(c+d) =", (a+b).dot(c+d))

# ============================================
# (h) PRODUCTOS CRUZ Y ÁNGULO CON d
# ============================================

print("\n--- (h) PRODUCTOS CRUZ ---")

ax_b = a.cross(b)
bx_c = b.cross(c)
cx_d = c.cross(d)

print("a × b =", ax_b.tolist())
print("b × c =", bx_c.tolist())
print("c × d =", cx_d.tolist())

print("\nÁngulo entre (a×b) y d:")
cos_t, theta = angulo_info(ax_b, d)
print("  cos(θ) =", cos_t)
print("  θ =", sp.N(theta,4), "rad")

# ============================================
# (i) PRODUCTO TRIPLE ESCALAR
# ============================================

print("\n--- (i) c · (a × b) ---")
print("c · (a × b) =", c.dot(ax_b))